### ISSUE TITLE
Parsing file

### ISSUE THREAD

**Issue by sgarro** [tvdstaaij/telegram-json-backup#6]
Hi there. 
So, I've never used a Json Lines file and there isn't much documentation.
I got a >100k messages backup file and i want to parse it with python so i can search and stuff, but i don't know how to do it

**Comment by xvilo** [comment]
Well the funny thing, in fact, is that there is a lot of documentation about Json. There is _also_ a lot of documentation about python!

This link should help you: http://bfy.tw/2GZR

**Comment by tvdstaaij** [comment]
There's not much documentation about it because there's not much to say, really :) It's just a text file with one JSON object per line. So you just [read the file line by line](https://stackoverflow.com/questions/8009882/how-to-read-large-file-line-by-line-in-python) and use [`json.loads`](https://docs.python.org/3/library/json.html) on each line. You then have a Python dictionary that you can use as you wish. To see what fields you can read from the dictionary, paste some lines of the jsonl file (one at a time) in [some](http://json.parser.online.fr/) [online](http://jsonviewer.stack.hu/) [json](http://codebeautify.org/jsonviewer) [beautifier](https://jsonformatter.curiousconcept.com/).

**Comment by sgarro** [comment]
Thank you so much, it wasn't that hard actually
